config/routes.rb
Depot::Application.routes.draw do

  mount RailsAdmin::Engine => '/user_admin', :as => 'rails_admin'
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :line_items
  resources :carts

  get "store/index"
  resources :products do
    get :who_bought, :on => :member
  end

  resources :orders do
    get :my_orders, :on => :collection
    resources :notes
  end

  root :to => 'store#index' , :as => 'store'

end

app/models/order.rb
class Order < ActiveRecord::Base
  PAYMENT_TYPES = [ "Check" , "Credit card" , "Purchase order" ]
  validates :name, :address, :email, :pay_type, :presence => true
  validates :pay_type, :inclusion => PAYMENT_TYPES
  has_many :line_items, :dependent => :destroy
  has_one :note, :dependent => :destroy
  paginates_per 10

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def maximum_orders?
    count_line_items >= 5
  end

  def minimum_orders?
    count_line_items <= 5
  end

  def count_line_items
    total_items = line_items.to_a.sum{ |q| q.quantity }
  end

  def total_price
    line_items.to_a.sum{ |total| total.quantity * total.product.price }
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :set_cart
  before_filter :set_user
  before_action :set_order, only: [:show, :edit, :update, :destroy ]

  skip_before_filter :authorize, :only => [:new, :create]

  # GET /orders
  # GET /orders.json
  def index
    @usr = current_user
    @orders = Order.order(:name).page(params[:page]).per(2)
    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @orders }
    end
  end


  # GET /orders/1
  # GET /orders/1.json
  def show
    @usr = current_user
    @count = @order.count_line_items
    @line_items = @order.line_items
    @total_price = @order.total_price
  end

  # GET /orders/new
  def new
    @cart = current_cart
    @usr = current_user
    if @cart.line_items.empty?
      redirect_to store_url, :notice => "Your cart is empty"
      return
    end
    @order = Order.new
    respond_to do |format|
      format.html # new.html.erb
      format.xml { render :xml => @order }
    end
  end


  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @cart = current_cart
    @usr = current_user
    @order = @usr.orders.new(order_params)
    @order.add_line_items_from_cart(current_cart)
    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil

        Notifier.order_received(@order).deliver

        format.html { redirect_to(store_url, :notice => 'Thank you for your order.' ) }
        format.xml { render :xml => @order, :status => :created, :location => @order }

      else
        format.html { render :action => "new" }
        format.xml { render :xml => @order.errors,:status => :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  def my_orders
    @user = current_user
    order = @user.orders
    if params[:order] == "max"
      @orders= order.select{ |list| list.maximum_orders? }
    else if   params[:order] == "min"
           @orders = order.select { |list| list.minimum_orders? }
         else
           @orders=order
         end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:name, :address, :email, :pay_type)
  end

  def set_cart
    @cart = current_cart
  end

  def set_user
    @usr = current_user
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
<% if @order.errors.any? %>
<div id="error_explanation" >
  <h2><%= pluralize(@order.errors.count, "error" ) %>
    prohibited this order from being saved:</h2>
  <ul>
    <% @order.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field" >
  <%= f.label :name %><br />
  <%= f.text_field :name, :size => 40 %>
</div>
<div class="field" >
  <%= f.label :address %><br />
  <%= f.text_area :address, :rows => 3, :cols => 40 %>
</div>
<div class="field" >
  <%= f.label :email %><br />
  <%= f.email_field :email, :size => 40 %>
</div>
<div class="field" >
  <%= f.label :pay_type %><br />
  <%= f.select :pay_type, Order::PAYMENT_TYPES, :prompt => 'Select a payment method' %>
</div>
<div class="actions" >
  <%= f.submit 'Place Order' %>
</div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Pay type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <td><%= order.pay_type %></td>
        <td><%= link_to 'Show', order %></td>
    
        <% if @usr.admin? %>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
 
        <td><%= link_to 'AddNote',new_order_note_path(order) %></td>
        <td><%= link_to 'EditNote',edit_order_note_path(order,order.note) %></td>
        </tr>
      <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New Order', new_order_path %>

<p><%= paginate @orders ,:window => 2 %></p>

app/views/orders/my_orders.html.erb
<h1>Listing orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Email</th>
      <th>Pay type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.address %></td>
        <td><%= order.email %></td>
        <td><%= order.pay_type %></td>
        
        <% if @user.admin? %>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>     
      </tr>
      <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'Min', my_orders_orders_path(order: "min") %>
<%= link_to 'Max', my_orders_orders_path(order: "max") %>


<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<div class="depot_form" >
  <fieldset>
    <legend>Please Enter Your Details</legend>
    <%= render 'form' %>
  </fieldset>
</div>

app/views/orders/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Pay type:</strong>
  <%= @order.pay_type %>
</p>

<table border="1">  
  <tr>
    <th>Product</th>
    <th>Price</th>
    <th>Quantity</th>
    <th>Cost</th>
  </tr>
  
  <%  @line_items.each do |item| %>
    <tr>
      <td><%= item.product.title %></td>  
      <td><%= item.product.price %></td>  
      <td><%= item.quantity %></td>  
      <td><%= item.quantity*item.product.price %></td>
    </tr>
   <% end %>
  <tr>
    <td> Total Price </td>
    <td><%= @total_price %>
  </tr>
</table>

<%= link_to 'Edit', edit_order_path(@order) %> |

<%= link_to 'Back', orders_path %>