config/routes.rb
Depot::Application.routes.draw do

  mount RailsAdmin::Engine => '/user_admin', :as => 'rails_admin'
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :line_items
  resources :carts

  get "store/index"
  resources :products do
    get :who_bought, :on => :member
  end

  resources :orders do
    get :my_orders, :on => :collection
    resources :notes
  end

  root :to => 'store#index' , :as => 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  paginates_per 50
  def add_product(product_id)
    current_item = line_items.where(:product_id => product_id).first
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def total_items
    line_items.sum(:quantity)
  end

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total_price
    product.price * quantity
  end

end

app/models/location.rb
class Location < ActiveRecord::Base

validates :address, :state, :country , :presence => true
validate :zipcode, length: { is: 5 }
has_many :users

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :order
end

app/models/order.rb
class Order < ActiveRecord::Base
  PAYMENT_TYPES = [ "Check" , "Credit card" , "Purchase order" ]
  validates :name, :address, :email, :pay_type, :presence => true
  validates :pay_type, :inclusion => PAYMENT_TYPES
  has_many :line_items, :dependent => :destroy
  has_one :note, :dependent => :destroy
  paginates_per 10

  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def maximum_orders?
    count_line_items >= 5
  end

  def minimum_orders?
    count_line_items <= 5
  end

  def count_line_items
    total_items = line_items.to_a.sum{ |q| q.quantity }
  end

  def total_price
    line_items.to_a.sum{ |total| total.quantity * total.product.price }
  end

end

app/models/product.rb
class Product < ActiveRecord::Base

  default_scope :order => 'title'
  has_many :line_items
  has_many :orders, :through => :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :image_url, :presence => true
  validates :price, :numericality => {:greater_than_or_equal_to => 0.01}
  validates :title, :uniqueness => true

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.count.zero?
      return true
    else
      errors.add(:base, 'Line Items present' )
      return false
    end
  end

end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
  validates :name, :presence => true, :uniqueness => true
  validates :password, :confirmation => true
  attr_accessor :password_confirmation
  attr_reader :password
  validate  :password_must_be_present
  after_destroy :ensure_an_admin_remains

  has_many :orders, :dependent => :destroy

  belongs_to :location

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "50x  50>" }, :default_url => "/images/:style/"

  accepts_nested_attributes_for :location

  def User.authenticate(name, password)
    if user = find_by_name(name)
      if user.hashed_password == encrypt_password(password, user.salt)
        user
      end
    end
  end

  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end

  def User.encrypt_password(password, salt)
    Digest::SHA2.hexdigest(password + "wibble" + salt)
  end

  # 'password' is a virtual attribute

  def password=(password)
    @password = password
    if password.present?
      generate_salt
      self.hashed_password = self.class.encrypt_password(password, salt)
    end
  end


  private

  def password_must_be_present
    errors.add(:password, "Missing password" ) unless hashed_password.present?
  end

  def generate_salt
    self.salt = self.object_id.to_s + rand.to_s
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :set_cart

  before_filter :set_user

  def index
    @total_orders = Order.count
    @usr = current_user
  end

  private

  def set_cart
    @cart = current_cart
  end

  def set_user
    @usr = current_user
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:edit, :update, :destroy]
  skip_before_filter :authorize, :only => [:create, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
    @user = current_user
  end


  # GET /carts/1
  # GET /carts/1.xml
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      Rails.logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, :notice => 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.xml { render :xml => @cart }
      end
    end
  end


  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create

    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to(store_url,:notice => 'Your cart is currently empty' ) }
      format.xml { head :ok }
    end

  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
  if condition
    attributes["style" ] = "display: none"
  end
    content_tag("div" , attributes, &block)
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/note_helper.rb
module NoteHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/admin/index.html.erb
<h1>Welcome</h1>
It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order" ) %>.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
</head>

<body id="store" >
<header>
  <div id="banner" >
    <%= image_tag("logo.png") %>
    <%= @page_title || "Pragmatic Bookshelf" %><br />
  
    <% if session[:user_id] %> 
    <a id="select" >User</a><br />
   
    <div class="list">
      
    <ul id="nav">
      <li> <%= link_to 'Profile',user_path(session[:user_id]) %></li>
      <li><%= link_to 'Settings',edit_user_path(session[:user_id])  %></li>
      <li><%= link_to 'Logout',logout_path, :method => :delete %></li>
    </ul>
    </div>

    <% end %>
    </div>

  </header>

    <div id="columns" >
      <div id="side" >
        <div>
          <%= hidden_div_if(@cart.line_items.empty?, :id => "cart" ) do %>
          <%= render @cart %>
          <% end %>
        </div>
        
        <%= link_to 'Home' ,store_path%><br />
        <a href="http://www..../questions" >Questions</a><br />
        <a href="http://www..../news" >News</a><br />
        <a href="http://www..../contact" >Contact</a><br />
        <%= link_to 'Sign In' ,login_path%><br />
        
        <% if session[:user_id] %> <br />
        <%= link_to 'MyOrders' ,my_orders_orders_path%><br />
        <%= link_to 'Products' ,products_path %><br />
        
        <% if @usr.admin? %>
        
        <%= link_to 'Admin',rails_admin_path %><br />
        <%= link_to 'Users' ,users_path%><br />
        <%= link_to 'Orders' ,orders_path%><br />
        
        <% end %>
        <br />
        
        <%= button_to 'Logout' , logout_path, :method => :delete %>
        <% end %>
        
      </div>

      <div id="main" >
        <%= yield %>
      </div>
    </div>
</body>
</html>

app/views/notifier/order_received.text.erb
Notifier#order_received
Dear <%= @order.name %>
Thank you for your recent order from The Pragmatic Store.
You ordered the following items:
<%= render @order.line_items %>
We'll send you a separate e-mail when your order ships

app/views/notifier/order_shipped.html.erb
<h3>Pragmatic Order Shipped</h3>
<p>
  This is just to let you know that we've shipped your recent order:
</p>
<table>
  <tr><th colspan="2" >Qty</th><th>Description</th></tr>
  <%= render @order.line_items %>
</table>